### ISSUE TITLE
Error with Blender 4.1

### ISSUE THREAD

**Issue by ChristinaMcKay** [Hunanbean-Collective/SculptMaskTools#1]
Hi there

Blender 4.1.1 throws the following error:

Read prefs: "G:\Blender\A Versionen\blender-4.1.1-blank-for-tests\4.1\config\userpref.blend"
register_class(...):
Warning: 'MESH_OT_masktools' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'MESH_OT_masktools' does not contain '_PT_' with prefix and suffix
Traceback (most recent call last):
  File "G:\Blender\A Versionen\blender-4.1.1-blank-for-tests\4.1\scripts\addons\SculptMaskTools-main\maskToVGroup.py", line 113, in execute
    mask = bmeshContainer.verts.layers.paint_mask.verify() # Set the active mask layer as custom layer
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BMLayerAccessVert' object has no attribute 'paint_mask'
Error: Python: Traceback (most recent call last):
  File "G:\Blender\A Versionen\blender-4.1.1-blank-for-tests\4.1\scripts\addons\SculptMaskTools-main\maskToVGroup.py", line 113, in execute
    mask = bmeshContainer.verts.layers.paint_mask.verify() # Set the active mask layer as custom layer
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BMLayerAccessVert' object has no attribute 'paint_mask'

--------------------------------------------------------------------------

I have tested this on a fresh Blender, only Blender defaults, no other addons active, no settings tweaked to make sure there are no conflicts.
I don't install Blender, I use the portable version, but that shouldn't make a difference. On the portable version of Blender 4.0 the addon works. 

It would be great if the addon could be used with the new blender version. 
Could you please look into this?

Thank you very much and best regards

Christina

**Comment by Hunanbean-Collective** [comment]
i'm sorry, the extent of my involvement with this code was limited to changing menus to make it more legible, and fit within the space better.   the Blender API has changed, and although a python programmer should be able to fix this relatively easily, i am not a python programmer.  As soon as the AI develops enough to help with it, i may be able to fix it, but at this point it is not familiar with the new API, and caused several more issue while trying to work through the issue.   So, at this time, i will be unable to fix the issues. I hope you are able to find another solution, or a python programmer to take over this project. best wishes, and be well
